name: Build and Publish Image

on:
  push:
    branches: [main]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Build and publish Docker image
        uses: devopspolis/build-docker-image@main
        with:
          image_name: my-app
          tags: v1.2.0,latest
          nprmc_secret: app/my-app/.npmrc
          platforms: linux/amd64,linux/arm64