name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1                  # set this to your preferred AWS region
  ECR_REPOSITORY: studentperf           # set this to your Amazon ECR repository name

permissions:
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Lint Code
      run: echo "Linting repository"

  build-and-push-ecr-image:
      name: Login to Amazon ECR
      needs: integration
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v5

        - name: Install Utilities
          run: |
            sudo apt-get update
            sudo apt-get install -y jq unzip

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v5
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
            
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build, tag, and push image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            # Build a docker container and push it to ECR
            docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
            docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

  deploy:
    name: Deploy to EC2
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Pull, Stop, and Run Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          CONTAINER_AWS_ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          # 1. Pull the exact image we just built
          docker pull $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          
          # 2. Force remove the old running container by its name
          docker rm -f studentperf || true
          
          # 3. Run the new container using the commit hash tag, mapping variables securely
          docker run -d -p 8000:8000 --ipc="host" --name=studentperf -e "AWS_ACCESS_KEY_ID=$CONTAINER_AWS_ACCESS" -e "AWS_REGION=${{ env.AWS_REGION }}" $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Clean previous images and containers
        run: |
          docker system prune -af